const AudiR8 = require('./images/audir8.png');
const BugattiDivo = require('./images/bugattidivo.png');
const CitroenBerlingo = require('./images/citroenberlingo.png');
const DaciaSandero = require('./images/daciasandero.png');
const FordFiesta = require('./images/fordfiesta.png');
const RenaultTwingo = require('./images/renaulttwingo.png');
const RenaultTwizy = require('./images/renaulttwizy.png');
const TeslaRoadster = require('./images/teslaroadster.png');
const OpelAstra = require('./images/opelastra.png');
const KiaSoul = require('./images/kiasoul.png');

export const CarsData = [
	{
		avalible: true,
		image: AudiR8,
		name: 'Audi R8',
		seats: 4,
		shifter: 'Ročni menjalnik',
		horsepower: 250,
		torque: 250,
		speed: 4.5,
		fuel: 'Dizel',
		location: 'Letališče Ljubljana',
		price: 200,
		duration: 3,
	},
	{
		avalible: true,
		image: OpelAstra,
		name: 'Opel Astra H GTC',
		seats: 5,
		shifter: 'Ročni menjalnik',
		horsepower: 105,
		torque: 150,
		speed: 12.1,
		fuel: 'Bencin',
		location: 'Letališče Ljubljana',
		price: 160,
		duration: 7,
	},
	{
		avalible: true,
		image: KiaSoul,
		name: 'Kia Soul EV',
		seats: 5,
		shifter: 'Avtomatski menjalnik',
		horsepower: 110,
		torque: 270,
		speed: 9,
		fuel: 'Elektrika',
		location: 'Gornji Grad',
		price: 20000,
		duration: 14,
	},
	{
		avalible: false,
		image: BugattiDivo,
		name: 'Bugatti Divo',
		seats: 2,
		shifter: 'Avtomatski menjalnik',
		horsepower: 500,
		torque: 669,
		speed: 2.5,
		fuel: 'Bencin',
		location: 'Letališče Ljubljana',
		price: 1200,
		duration: 2,
	},
	{
		avalible: true,
		image: CitroenBerlingo,
		name: 'Citroen Berlingo',
		seats: 5,
		shifter: 'Ročni menjalnik',
		horsepower: 90,
		torque: 80,
		speed: 11,
		fuel: 'Bencin',
		location: 'Letališče Ljubljana',
		price: 200,
		duration: 1,
	},
	{
		avalible: true,
		image: DaciaSandero,
		name: 'Dacia Sandero',
		seats: 5,
		shifter: 'Ročni menjalnik',
		horsepower: 100,
		torque: 100,
		speed: 8.5,
		fuel: 'Plin',
		location: 'Gornji Grad',
		price: 100,
		duration: 5,
	},
	{
		avalible: true,
		image: FordFiesta,
		name: 'Ford Fiesta',
		seats: 5,
		shifter: 'Ročni menjalnik',
		horsepower: 240,
		torque: 100,
		speed: 5.5,
		fuel: 'Bencin',
		location: 'Juvanje',
		price: 150,
		duration: 4,
	},
	{
		avalible: true,
		image: RenaultTwingo,
		name: 'Renault Twingo',
		seats: 5,
		shifter: 'Ročni menjalnik',
		horsepower: 69,
		torque: 90,
		speed: 3.5,
		fuel: 'Bencin',
		location: 'Letališče Ljubljana',
		price: 690,
		duration: 3,
	},
	{
		avalible: true,
		image: RenaultTwizy,
		name: 'Renault Twizy',
		seats: 2,
		shifter: 'Avtomatski menjalnik',
		horsepower: 10,
		torque: 9999,
		speed: 0.5,
		fuel: 'Elektrika',
		location: 'Letališče Ljubljana',
		price: 10,
		duration: 1,
	},
	{
		avalible: true,
		image: TeslaRoadster,
		name: 'Tesla Roadster',
		seats: 2,
		shifter: 'Avtomatski menjalnik',
		horsepower: 250,
		torque: 250,
		speed: 1.5,
		fuel: 'Elektrika',
		location: 'Šoštanj',
		price: 5000,
		duration: 2,
	},
];
